### ISSUE TITLE
Video: Quick Cache (Lite) → ZenCache (Lite)

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache-kb#17]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

```yaml
title: Video: Quick Cache (Lite) → ZenCache (Lite)
categories: tutorials
tags: 
author: raamdev
github-issue: https://github.com/websharks/zencache-kb/issues/17
```
---

_This is a placeholder issue for the video that needs to be done as part of the Quick Cache (Lite) → ZenCache (Lite) Migration Article (see websharks/zencache-kb#12). The video cannot be done until ZenCache has been published to WordPress.org, so that it can show ZenCache being installed from the WordPress.org plugin repo._

_When done, this video tutorial should be added to the top of the websharks/zencache-kb#12 KB Article._
