### ISSUE TITLE
If a request is made to a CDN that happens to be down, what happens? Does the user get routed to the next closest CDN?

### ISSUE THREAD

**Issue by jaswsinc** [websharks/zencache-kb#42]
---
##### KB Article Creation Checklist

- [ ] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [ ] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [ ] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

```yaml
title: If a request is made to a CDN that happens to be down, what happens? Does the user get routed to the next closest CDN?
categories: questions
tags: static-cdn-filters
author: jaswsinc
github-issue: https://github.com/websharks/zencache-kb/issues/42
```
---

This behavior will vary from one CDN to the next; i.e., it depends on who your CDN provider is, and in how you configure it. However, the answer to your question is almost aways a big **yes**! That's one of the most useful features that a CDN can offer; i.e., it is one of the reasons for using a CDN to begin with. It is best to consult with your CDN though. Or, read over the documentation they provide.
