### ISSUE TITLE
Why do I get SSL Mixed Content Errors when clicking the "Clear Cache" and "Wipe" buttons?

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache-kb#44]
---
##### KB Article Creation Checklist

- [ ] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [ ] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [ ] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

```yaml
title: Why do I get SSL Mixed Content Errors when clicking the "Clear Cache" and "Wipe" buttons?
categories: questions
tags: error-messages
author: raamdev
github-issue: https://github.com/websharks/zencache-kb/issues/44
```
---
ZenCache uses the [WordPress `is_ssl()` function](http://codex.wordpress.org/Function_Reference/is_ssl) to detect if your site is using `http://` or `https://`. However, the WordPress `is_ssl()` function can have trouble properly detecting which protocol you're using if your site is behind a load balancer, such as when you're using CloudFlare with Flexible SSL. 

Please see this article for more information: http://snippets.webaware.com.au/snippets/wordpress-is_ssl-doesnt-work-behind-some-load-balancers/

Unfortunately there isn't anything that can be done on the ZenCache side of things. You might want to look into fixing things so that `is_ssl()` is always reliable while using CloudFlare. Otherwise, this issue shouldn't be affecting the operation of ZenCache itself.
