### ISSUE TITLE
Why doesn't ZenCache integrate with CloudFlare?

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache-kb#50]
---
##### KB Article Creation Checklist

- [ ] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [ ] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [ ] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

```yaml
title: Why doesn't ZenCache integrate with CloudFlare?
categories: questions
tags: static-cdn-filters
author: raamdev
github-issue: https://github.com/websharks/zencache-kb/issues/50
```
---
[needs to be drafted]
[insert diagram that shows how CloudFlare works and where ZenCache fits in]

### How do other plugins (such as W3TC) integrate with CloudFlare?

Plugins like W3TC don't actually integrate with the CloudFlare caching infrastructure at all. They simply provide options that let you control your CloudFlare account remotely (i.e., from inside the WordPress Dashboard instead of from the CloudFlare Dashboard). These options just let you enable/disable certain CloudFlare features--the plugin isn't actually doing anything with the CloudFlare cache.

[insert diagram]
