### ISSUE TITLE
Building an AC (Advanced Cache) Plugin

### ISSUE THREAD

**Issue by jaswsinc** [websharks/zencache-kb#63]
---
##### KB Article Creation Checklist

- [ ] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [ ] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [ ] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

```yaml
title: Building an AC (Advanced Cache) Plugin
categories: tutorials
tags: 
author: jaswsinc
github-issue: https://github.com/websharks/zencache-kb/issues/63
```
---

Example script: http://bit.ly/1DnFDNz

_[article needs to be written]_
