### ISSUE TITLE
Why aren't my font icons loading with Static CDN Filters enabled?

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache-kb#67]
---
##### KB Article Creation Checklist

- [ ] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [ ] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [ ] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

```yaml
title: Why aren't my font icons loading with Static CDN Filters enabled?
categories: questions
tags: static-cdn-filters
author: raamdev
github-issue: https://github.com/websharks/zencache-kb/issues/67
```
---
If you've excluded font file extensions in Static CDN Filters and also tried excluding the URIs to the font files, and you still experience an issue, then the issue may be that you have a CSS file that is referencing font files using relative paths like `url('../fonts/icomoon.eot')` and when the Static CDN Filters serves those CSS files via your CDN, the fonts were not able to load (the path of `../fonts/icomoon.eot` does not exist on the CDN). I was able to fix this by specifically excluding those two CSS files from the Static CDN Filter.

```
*icomoon.css*
*essb-fanscount*.css*
```
