### ISSUE TITLE
Is ZenCache compatible with Varnish?

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache-kb#75]
---
##### KB Article Creation Checklist

- [ ] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [ ] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [ ] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

```yaml
title: Is ZenCache compatible with Varnish?
categories: questions
tags: 
author: raamdev
github-issue: https://github.com/websharks/zencache-kb/issues/75
```
---
[Needs to be drafted.]

[See ZenCache Feature Request to add support for Varnish: https://github.com/websharks/zencache/issues/342]

[Also, we need to run some internal tests with Varnish + ZenCache.]
